networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
## NGINX ###################################
  nginx:
    build:
      context: ./nginx
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ${WORKSPACE_HOST_PATH}:/var/www:delegated
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available:delegated
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    networks:
      - backend