networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
## NGINX ###################################
  nginx:
    build:
      context: ./nginx
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ${WORKSPACE_HOST_PATH}:/var/www:delegated
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available:delegated
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    depends_on:
      - php-fpm
    networks:
      - backend

## PHP-FPM ###################################
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - PHP_VERSION=${PHP_VERSION:-8.3}
    volumes:
      - ${WORKSPACE_HOST_PATH}:/var/www:delegated
    networks:
      - backend
